### ISSUE TITLE
stopwords_for_language has stopped working

### ISSUE THREAD

**Issue by pgulley** [mediacloud/mc-providers#28]
It looks like we're no longer packaging this with the *.txt files that power the stopwords system- looks like a pypackage.toml issue.

**Comment by pgulley** [comment]
Attempted to address this by making a change in pypackage.toml, but it doesn't seem to have worked!

**Comment by kilemensi** [comment]
Not too familiar with this codebase but looking at `pyproject.toml`, I think it's missing [build system section](https://flit.pypa.io/en/stable/pyproject_toml.html#build-system-section): `python3 -m build` may need to be told to use `flit` so that it can process `[tool.flit.sdist]` correctly

**Comment by pgulley** [comment]
Yep, adding a build-systems setting fixed this- stop words are now available through that interface. Good catch, thank you!
